---
title: "EDS 221 - Day 1 Tasks"
author: "Paloma Cartwright"
date: "09/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(skimr)
library(dplyr)
```


```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"), skip = 1) %>% 
  clean_names() %>% 
  mutate(pct_elevated = str_replace(pct_elevated, 
                                    pattern = ",", 
                                    replacement = ".")) %>% 
  mutate(pct_elevated = as.numeric(pct_elevated))
```
## Insert some code to explore the dataset here

I didnt do this yet because I was trying to catch up after my bad github cloning moments. 

## Clean names using the janitor function 
```{r}
clean_names(stl_lead)
```

## Create a new Data Frame 

```{r}
stl_lead_prop <- stl_lead %>%  mutate(prop_white = white / total_pop * 100)
```

## Create a scatter plot 

The higher percentage of lead in your blood, the less likely you are white. 
```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, 
                                                  y = prop_white)) + 
  geom_point(aes(color = pct_elevated)) + 
  scale_color_gradient(low = "blue", high = "orange") +
  labs(title = "Elevated levels of Lead in Blood versus Race", 
       x = "Percentage of Lead in Blood", 
       y = "Percentage of Population Identifying as White")
stl_lead_plot
ggsave(here::here("figs", "stl_lead_plot.jpeg"))
ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```

## Create a Histogram 

```{r}
stl_lead_hist <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(fill = "blue", color = "black") +
  labs(title = "Percentages of Elevated Lead in Blood",
       x = "Percentages of Lead in Blood", 
       y = "")

stl_lead_hist

ggsave(here::here("figs", "stl_lead_hist.jpg"), height = 7, width = 7)
```

